/* STOCK DATA REQUEST ACTION TYPES*/
export const STOCK_DATA_REQUEST = 'STOCK_DATA_REQUEST';
export const STOCK_DATA_REQUEST_SUCCESS = 'STOCK_DATA_REQUEST_SUCCESS';
export const STOCK_DATA_CHANGE_VIEW = 'STOCK_DATA_CHANGE_VIEW';
export const STOCK_DATA_REQUEST_FAIL = 'STOCK_DATA_REQUEST_FAIL';
export const STOCK_DATA_REQUEST_SORT = 'STOCK_DATA_REQUEST_SORT';

export const RESIZE_WINDOW = 'RESIZE_WINDOW';
